services:
  aphw-ddi-notifications:
    build:
      context: .
      target: production
    image: aphw-ddi-notifications
    container_name: aphw-ddi-notifications
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-notifications-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-test}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-test}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-test}
      NOTIFICATIONS_QUEUE_ADDRESS: ${NOTIFICATIONS_QUEUE_ADDRESS:-aphw-ddi-notifications}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_TOPIC_ADDRESS: ${EVENT_TOPIC_ADDRESS:-aphw-ddi-events}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_SUBSCRIPTION_ADDRESS: ${EVENT_SUBSCRIPTION_ADDRESS:-aphw-ddi-event-hub}${MESSAGE_QUEUE_SUFFIX}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY:-test}
      GENERIC_ERROR_TEMPLATE_ID: ${GENERIC_ERROR_TEMPLATE_ID:-41841362-ed61-44e6-bbf3-4449e86c895f}
      VERIFY_EMAIL_TEMPLATE_ID: ${VERIFY_EMAIL_TEMPLATE_ID:-d4ba9e8a-ce71-49a1-b6cf-fce5c0844ab3}
      USER_FEEDBACK_TEMPLATE_ID: ${USER_FEEDBACK_TEMPLATE_ID:-ed19c634-d5c2-410f-a22b-2f2f8d64c9a9}
      USER_INVITE_TEMPLATE_ID: ${USER_INVITE_TEMPLATE_ID:-c4ae359f-1fa3-4ed4-ab96-5c33ff7ba0a9}
      REPORT_SOMETHING_TEMPLATE_ID: ${REPORT_SOMETHING_TEMPLATE_ID:-25c2026d-523a-4e83-a0e2-085d84fed8ef}
      FORM2_SUBMISSION_TO_DEFRA_TEMPLATE_ID: ${FORM2_SUBMISSION_TO_DEFRA_TEMPLATE_ID:-9398791e-1e43-4c54-989b-1b8f7eed19c7}
      FORM2_CONFIRMATION_TO_POLICE_TEMPLATE_ID: ${FORM2_CONFIRMATION_TO_POLICE_TEMPLATE_ID:-870e5832-d0e1-4902-a1bc-033a467d5cf2}
