# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  aphw-ddi-notifications:
    build:
      target: development
    image: aphw-ddi-notifications-development
    container_name: aphw-ddi-notifications-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    depends_on:
      - aphw-ddi-notifications-azurite
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://aphw-ddi-documents-azurite:10000/devstoreaccount1;"
      AZURE_STORAGE_CERTIFICATE_TEMPLATE_CONTAINER: "certificate-templates"

  aphw-ddi-notifications-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.30.0