services:
  aphw-ddi-notification:
    build:
      context: .
      target: production
    image: aphw-ddi-notification
    container_name: aphw-ddi-notification
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-notification-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
