services:
  aphw-ddi-notification:
    build:
      context: .
      target: production
    image: aphw-ddi-notification
    container_name: aphw-ddi-notification
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-notification-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      NOTIFICATIONS_QUEUE_ADDRESS: ${NOTIFICATIONS_QUEUE_ADDRESS:-aphw-ddi-notifications}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_TOPIC_ADDRESS: ${EVENT_TOPIC_ADDRESS:-dangerous-dogs-index-events}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_SUBSCRIPTION_ADDRESS: ${EVENT_SUBSCRIPTION_ADDRESS:-dangerous-dogs-index-event-hub}${MESSAGE_QUEUE_SUFFIX}
      NOTIFY_API_KEY: ${DDI_NOTIFY_API_KEY:-test}
