environment: production
environmentCode:
name: aphw-ddi-notifications
namespace: aphw-ddi
workstream: aphw-ddi
image: aphw-ddi-notifications

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: aphw-ddi-notifications-config-map

containerSecret:
  name: aphw-ddi-notifications-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  messageQueueHost: host
  notifyApiKey: notifyApiKey
  genericErrorTemplateId: dummy
  verifyEmailTemplateId: dummy
  userFeedbackTemplateId: dummy
  userInviteTemplateId: dummy
  reportSomethingTemplateId: dummy
  notificationsQueueAddress: aphw-ddi-notifications
  eventsTopicAddress: aphw-ddi-events
  eventsSubscriptionAddress: aphw-ddi-event-hub

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
