{{- include "ffc-helm-library.container-config-map" (list . "aphw-ddi-notifications.config-map") -}}
{{- define "aphw-ddi-notifications.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  GENERIC_ERROR_TEMPLATE_ID: {{ quote .Values.container.genericErrorTemplateId }}
  VERIFY_EMAIL_TEMPLATE_ID: {{ quote .Values.container.verifyEmailTemplateId }}
  USER_FEEDBACK_TEMPLATE_ID: {{ quote .Values.container.userFeedbackTemplateId }}
  USER_INVITE_TEMPLATE_ID: {{ quote .Values.container.userInviteTemplateId }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  NOTIFICATIONS_QUEUE_ADDRESS: {{ .Values.container.notificationsQueueAddress }}-{{ .Values.environmentCode }}
  EVENTS_TOPIC_ADDRESS: {{ .Values.container.eventsTopicAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  NOTIFICATIONS_QUEUE_ADDRESS: {{ quote .Values.container.notificationsQueueAddress }}
  EVENTS_TOPIC_ADDRESS: {{ quote .Values.container.eventsTopicAddress }}
  {{- end }}
  EVENTS_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.eventsSubscriptionAddress }}
{{- end -}}
