{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-notifications.container-secret") -}}
{{- define "aphw-ddi-notifications.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.appInsights.messageQueueHost }}
  MESSAGE_QUEUE_PASSWORD: {{ quote .Values.appInsights.messageQueuePassword }}
  MESSAGE_QUEUE_USER: {{ quote .Values.appInsights.messageQueueUser }}
  NOTIFY_API_KEY: {{ quote .Values.appInsights.notifyApiKey }}
  {{- end }}
{{- end -}}
