{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-notifications.container-secret") -}}
{{- define "aphw-ddi-notifications.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
{{/*  MESSAGE_QUEUE_PASSWORD: {{ quote .Values.container.messageQueuePassword }}*/}}
{{/*  MESSAGE_QUEUE_USER: {{ quote .Values.container.messageQueueUser }}*/}}
  NOTIFY_API_KEY: {{ quote .Values.container.notifyApiKey }}
  {{- end }}
{{- end -}}
